language: php

php:
 - 5.4

before_script:
  - pear install PHP_CodeSniffer
  - phpenv rehash
  - ./composer.phar install --dev --prefer-source --no-interaction

script:
  - phpcs --standard=psr2 ./src
  - ./vendor/bin/phpmd src/ text codesize,controversial,design,naming,unusedcode
  - ./vendor/bin/phpunit